import fs from 'fs';
import path from 'path';
import { describe, expect, it } from 'vitest';

function readSource(filePath) {
    return fs.readFileSync(path.resolve(filePath), 'utf8');
}

describe('json-format settings regression guards', () => {
    it('uses explicit defaults for content-script json-format options', () => {
        const source = readSource('apps/background/background.js');

        expect(source).toContain('const defaultOptions = {');
        expect(source).toContain('JSON_TOOL_BAR_ALWAYS_SHOW: true');
        expect(source).toContain('ENABLE_JSON_KEY_SORT: true');
        expect(source).toContain('NESTED_ESCAPE_PARSE: false');
        expect(source).toContain('AUTO_TEXT_DECODE: false');
        expect(source).toContain('JSON_FORMAT_COMPACT_MODE: true');
        expect(source).toContain("FH_UI_MODE: 'lite'");
        expect(source).toContain("JSON_FORMAT_UI_MODE: 'lite'");
        expect(source).toContain("JSON_FORMAT_EXCLUDED_ORIGINS: ''");
        expect(source).toContain("const migrated = String(result.FH_JSONFORMAT_DEFAULTS_MIGRATED) === 'true';");
        expect(source).toContain('if (Array.isArray(params)) {');
        expect(source).toContain("} else if (typeof params === 'string') {");
        expect(source).toContain("storageQuery = {FH_JSONFORMAT_DEFAULTS_MIGRATED: false};");
        expect(source).toContain("storageQuery[key] = defaultOptions.hasOwnProperty(key) ? defaultOptions[key] : params[key];");
        expect(source).toContain("const stringOptions = ['FH_UI_MODE', 'JSON_FORMAT_UI_MODE'];");
        expect(source).toContain("const rawStringOptions = ['JSON_FORMAT_EXCLUDED_ORIGINS'];");
        expect(source).toContain("} else if (rawStringOptions.includes(key)) {");
        expect(source).toContain("result.JSON_TOOL_BAR_ALWAYS_SHOW = true;");
        expect(source).toContain("result.ENABLE_JSON_KEY_SORT = true;");
        expect(source).toContain("result.NESTED_ESCAPE_PARSE = false;");
        expect(source).toContain("ENABLE_JSON_KEY_SORT: 'true'");
        expect(source).toContain("NESTED_ESCAPE_PARSE: 'false'");
        expect(source).toContain("FH_JSONFORMAT_DEFAULTS_MIGRATED: 'true'");
        expect(source).toContain("result[key] === undefined || result[key] === null || result[key] === ''");
        expect(source).not.toContain('result[key] = (""+result[key] !== \'false\');');
    });

    it('manual json-format page no longer silently inherits legacy nested-parse keys', () => {
        const source = readSource('apps/json-format/index.js');
        const html = readSource('apps/json-format/index.html');
        const css = readSource('apps/json-format/index.css');

        expect(source).toContain("this.nestedEscapeParse = (this.safeGetLocalStorage('jsonformat:nested-escape-parse') === 'true');");
        expect(source).toContain("let FH_UI_MODE = 'FH_UI_MODE';");
        expect(source).toContain("let JSON_FORMAT_UI_MODE = 'JSON_FORMAT_UI_MODE';");
        expect(source).toContain("document.body.classList.toggle('fh-ui-mode-lite', isLiteMode);");
        expect(source).toContain("chrome.storage.local.get([JSON_FORMAT_UI_MODE, FH_UI_MODE], result => {");
        expect(source).toContain("this.uiMode = String(result[JSON_FORMAT_UI_MODE] || result[FH_UI_MODE] || '').toLowerCase() === 'omni' ? 'omni' : 'lite';");
        expect(html).toContain("['fh-top-shell', uiMode === 'lite' ? 'is-lite' : 'is-omni']");
        expect(html).toContain("v-if=\"uiMode === 'lite'\"");
        expect(html).toContain('请作者喝咖啡');
        expect(html).not.toContain('>设置</button>');
        expect(html).toContain('class="fh-header-actions fh-header-actions-omni"');
        expect(html).toContain('class="fh-header-tail fh-header-tail-omni"');
        expect(html).toContain('class="fh-lite-support fh-donate-action"');
        expect(html).toContain(":class=\"{selected: currentLayout === 'left-right'}\"");
        expect(html).toContain(":class=\"{selected: currentLayout === 'up-down'}\"");
        expect(html).toContain("@click=\"setUiMode('lite')\"");
        expect(html).toContain("@click=\"setUiMode('omni')\"");
        expect(css).toContain('.fh-top-shell.is-lite');
        expect(css).toContain('.fh-json-tool.fh-json-tool-lite .fh-tool-header');
        expect(css).toContain('.fh-json-tool.fh-json-tool-lite {\n    padding: 4px 5px 5px;\n    gap: 5px;');
        expect(css).toContain('.fh-json-tool.fh-json-tool-lite .fh-tool-header {\n    min-height: 38px;\n    padding: 4px 9px;');
        expect(css).toContain('.fh-json-tool.fh-json-tool-lite .fh-mode-note');
        expect(css).toContain('.fh-json-tool.fh-json-tool-lite .fh-lite-support {\n    height: 26px;');
        expect(css).toContain('.fh-header-right-omni');
        expect(css).toContain('.fh-toolbar-tail-omni');
        expect(css).toContain('.fh-header-tail-omni');
        expect(css).toContain('html.fh-jf .fh-segmented > button.selected');
        expect(source).toContain("currentLayout: 'left-right'");
        expect(source).toContain("this.currentLayout = this.normalizeLayout(this.safeGetLocalStorage(LOCAL_KEY_OF_LAYOUT));");
        expect(source).toContain("this.$nextTick(() => {");
        expect(source).toContain("this.changeLayout(this.currentLayout);");
        expect(source).toContain("const selectedSortInput = document.querySelector('[name=\"jsonsort\"]:checked');");
        expect(source).toContain("const sortType = selectedSortInput ? selectedSortInput.value : '0';");
        expect(html).toContain('<section class="fh-inline-command-bar" aria-label="JSON 主要操作" v-if="uiMode === \'lite\'">');
        expect(html).not.toContain('fh-lite-toggle-group');
        expect(html).not.toContain('@click="toggleNestedEscapeParse"');
        expect(html).toContain('查看原文');
        expect(html).toContain('关闭嵌套解析后重试');
        expect(source).toContain('const RAW_FALLBACK_PREVIEW_LIMIT = 12000;');
        expect(source).toContain('buildRawFallbackHtml(source, options = {})');
        expect(source).toContain('showRawFallbackResult(full = false)');
        expect(source).toContain('showFullRawFallbackResult()');
        expect(source).toContain('rawFallbackTruncated');
        expect(source).toContain('retryWithoutNestedEscapeParse()');
        expect(source).not.toContain('toggleNestedEscapeParse()');
        expect(source).toContain('buildErrorPlaceholder(message)');
        expect(css).toContain('.fh-json-error-actions');
        expect(css).toContain('.fh-raw-fallback-pre');
        expect(css).toContain('.fh-error-state');
        expect(html).not.toContain('<section class="fh-inline-command-bar" aria-label="JSON 主要操作" v-if="uiMode === \'lite\'">\n                        <div class="fh-command-group fh-command-primary">');
        expect((html.match(/id="btnFormat"/g) || []).length).toBe(1);
        expect(html).not.toContain("showLiteAdvanced");
        expect(source).not.toContain('jsonformat:auto-unpack-json-string');
        expect(source).not.toContain('jsonformat:escape-json-string');
    });

    it('content-script scopes advanced auto-format controls to Omni mode', () => {
        const source = readSource('apps/json-format/content-script.js');
        const cssSource = readSource('apps/json-format/content-script.css');
        const formatLibSource = readSource('apps/json-format/format-lib.js');
        const backgroundSource = readSource('apps/background/background.js');

        expect(source).toContain("JSON_FORMAT_COMPACT_MODE: 'JSON_FORMAT_COMPACT_MODE'");
        expect(source).toContain("FH_UI_MODE: 'FH_UI_MODE'");
        expect(source).toContain("JSON_FORMAT_UI_MODE: 'JSON_FORMAT_UI_MODE'");
        expect(source).toContain("JSON_FORMAT_EXCLUDED_ORIGINS: 'JSON_FORMAT_EXCLUDED_ORIGINS'");
        expect(source).toContain('if (!window.__FH_JSON_AUTO_FORMAT_SCRIPT_LOADED__) {');
        expect(source).toContain('window.__FH_JSON_AUTO_FORMAT_SCRIPT_LOADED__ = true;');
        expect(source.indexOf('if (!window.__FH_JSON_AUTO_FORMAT_SCRIPT_LOADED__) {')).toBeLessThan(source.indexOf('window.JsonAutoFormat = (() => {'));
        expect(source.indexOf('window.JsonAutoFormat = (() => {')).toBeLessThan(source.indexOf('await window.JsonAutoFormat.format();'));
        expect(source).toContain("document.documentElement.classList.add('fh-jf');");
        expect(source).toContain('class="setting-section-title">运行</div>');
        expect(source).toContain('class="setting-section-title">解析与排序</div>');
        expect(source).toContain('class="setting-section-title">显示</div>');
        expect(source).toContain('class="setting-donate-link"');
        expect(source).toContain('请作者喝咖啡');
        expect(source).toContain("input type=\"checkbox\" name=\"nestedParse\"");
        expect(source).not.toContain("input type=\"checkbox\" name=\"compactMode\"");
        expect(source).not.toContain("默认使用紧凑视图");
        expect(source).not.toContain("id=\"nestedEscapeParseToggle\"");
        expect(source).not.toContain("id=\"compactModeToggle\"");
        expect(source).toContain("body.classList.toggle('fh-ui-mode-lite', isLiteMode);");
        expect(source).toContain('class="fh-auto-mode-switch"');
        expect(source).toContain('class="fh-viewbar-group fh-omni-tools"');
        expect(source).toContain('id="fhJsonSearchInput"');
        expect(source).toContain("data-json-ui-mode=\"lite\"");
        expect(source).toContain("data-json-ui-mode=\"omni\"");
        expect(source).toContain("Formatter.search(query)");
        expect(source).toContain("Formatter.copySelectedPath");
        expect(source).toContain("Formatter.copySelectedValue");
        expect(source).toContain("Formatter.collapseAll");
        expect(source).toContain("Formatter.expandAll");
        expect(source).toContain("Formatter.clearSelection");
        expect(source).not.toContain('id="fhJsonExpandAll"');
        expect(source).not.toContain('id="fhJsonCollapseAll"');
        expect(source).not.toContain('id="fhJsonRawToggle"');
        expect(source).not.toContain('id="fhJsonSelectionPath"');
        expect(source).not.toContain('id="fhJsonSelectionMeta"');
        expect(source).toContain("_isCurrentOriginExcluded()");
        expect(source).toContain("let _toggleCurrentOriginExclusion = () => {");
        expect(source).toContain("list = list.filter(item => !_matchesCurrentOriginPattern(item));");
        expect(source).toContain("_mountExcludedOriginToolbar();");
        expect(source).toContain("window.location.reload();");
        expect(source).toContain("id=\"fhJsonExcludedOriginPrompt\"");
        expect(source).toContain("aria-expanded=\"true\"");
        expect(source).toContain("translateX(calc(100% - 36px))");
        expect(source).toContain("let _setToolbarTucked = tucked => {");
        expect(source).toContain("toolbar.style.transform = '';");
        expect(source).toContain("_scheduleToolbarAutoTuck(1500);");
        expect(source).toContain("toolbar.addEventListener('mouseenter'");
        expect(source).toContain("toolbar.addEventListener('mouseleave'");
        expect(source).toContain("class=\"fh-collapse-icon\"");
        expect(source).toContain("role=\"button\" tabindex=\"0\"");
        expect(source).toContain("aria-label=\"收起工具栏\"");
        expect(source).toContain("$('.fe-feedback .fh-collapse-icon').attr('aria-label'");
        expect(source).toContain("$('.fe-feedback .fh-collapse-icon').on('click'");
        expect(source).toContain("$('.fe-feedback .fh-collapse-icon').on('keydown'");
        expect(source).toContain("_saveJsonFormatOptions({JSON_TOOL_BAR_ALWAYS_SHOW: showToolBar});");
        expect(source).toContain("class=\"fh-toggle-label\">收起</span>");
        expect(source).not.toContain("id=\"toggleBtn\" title=\"收起工具栏\" aria-expanded=\"true\"><img");
        expect(source).toContain("_scheduleExcludedOriginPromptAutoTuck(1500);");
        expect(source).toContain("prompt.addEventListener('mouseenter'");
        expect(source).toContain("prompt.addEventListener('mouseleave'");
        expect(source).toContain("prompt.addEventListener('focusin'");
        expect(source).toContain("prompt.addEventListener('focusout'");
        expect(source).toContain("恢复JSON美化");
        expect(source).toContain("border-radius:6px 0 0 6px");
        expect(source).toContain("padding:4px 8px 4px 6px");
        expect(source).toContain("width:22px;height:22px;flex:0 0 22px;margin:0;");
        expect(source).toContain("box-shadow:-2px 5px 14px rgba(15,23,42,.1)");
        expect(source).toContain("background:transparent;box-shadow:none;color:#2563eb");
        expect(source).toContain("font:800 12px/22px");
        expect(source).not.toContain("background:linear-gradient(180deg,#f0fdf4 0%,#bbf7d0 100%)");
        expect(source).toContain("button.addEventListener('mousedown'");
        expect(source).not.toContain("FH 已排除此站");
        expect(source).toContain("class=\"xjf-btn\" id=\"fhJsonExcludeSite\">排除此站</button>");
        expect(source.indexOf("class=\"xjf-btn\" id=\"fhJsonExcludeSite\">排除此站</button>")).toBeGreaterThan(source.indexOf("fh-viewbar-actions"));
        expect(source).not.toContain("fh-json-excluded-toolbar");
        expect(source).not.toContain("此站已排除自动格式化");
        expect(source).toContain("formatOptions.JSON_FORMAT_EXCLUDED_ORIGINS = String(options.JSON_FORMAT_EXCLUDED_ORIGINS || '');");
        expect(source).toContain("formatOptions.FH_UI_MODE = String(options.FH_UI_MODE || '').toLowerCase() === 'omni' ? 'omni' : 'lite';");
        expect(source).toContain("formatOptions.JSON_FORMAT_UI_MODE = String(options.JSON_FORMAT_UI_MODE || '').toLowerCase() === 'omni' ? 'omni' : 'lite';");
        expect(source.indexOf("_syncExcludeSiteButtonState();")).toBeLessThan(source.indexOf("if (!isOmni) {"));
        expect(source).toContain("const forceCompact = _getResolvedUiMode() !== 'omni';");
        expect(source).toContain('const liveCheckboxOptions = {');
        expect(source).toContain("nestedParse: {key: 'NESTED_ESCAPE_PARSE', reformat: true}");
        expect(source).not.toContain("compactMode: {key: 'JSON_FORMAT_COMPACT_MODE', reformat: false}");
        expect(source).not.toContain('sPanel.find(\'input[name="compactMode"]\')');
        expect(source).toContain('sPanel.find(\'input[type="checkbox"]\').on(\'change\', function () {');
        expect(source).toContain('sPanel.find(\'input[name="maxlength"]\').on(\'change\', function () {');
        expect(source).toContain('sPanel.find(\'input[name="skinId"]\').on(\'change\', function () {');
        expect(source).toContain('applyPanelOptions(params, {reformat: config.reformat});');
        expect(source).toContain('savePanelOptions(params);');
        expect(source).toContain('_syncFormatterEscapeState();');
        expect(source).toContain('_syncFormatterStatusBarState();');
        expect(source).toContain('_applyToolbarDisplayState();');
        expect(source).toContain("sPanel.find('.setting-donate-link').on('click', _openDonateModal);");
        expect(source).toContain("thing: 'open-donate-modal'");
        expect(formatLibSource).toContain('let statusBarEnabled = true;');
        expect(formatLibSource).toContain('setStatusBarEnabled: function(enabled)');
        expect(formatLibSource).toContain('search: function(query)');
        expect(formatLibSource).toContain('copySelectedPath: function()');
        expect(formatLibSource).toContain('copySelectedValue: function()');
        expect(formatLibSource).toContain('collapseAll: function()');
        expect(formatLibSource).toContain('expandAll: function()');
        expect(formatLibSource).toContain('togglePlainJsonView: function(enabled)');
        expect(formatLibSource).toContain('clearSelection: function()');
        expect(formatLibSource).toContain("let _clearSelection = function () {");
        expect(formatLibSource).toContain("let _getExplicitSelectedJsonElement = function () {");
        expect(formatLibSource).toContain("toast('请先选中一个 JSON 节点。');");
        expect(formatLibSource).toContain("$('#jsonPath,#jsonSelectionMeta').text('').removeAttr('title');");
        expect(formatLibSource).toContain("'<span id=\"jsonSelectionMeta\"/>");
        expect(formatLibSource).toContain("document.dispatchEvent(new CustomEvent('fh-json-selection-change'");
        expect(formatLibSource).toContain('function shouldWrapLongString(value)');
        expect(formatLibSource).toContain("const lineClass = wrapLongString ? 'item item-line item-line-wrap' : 'item item-line';");
        expect(formatLibSource).toContain("selected = $('#jfContent .item').first();");
        expect(backgroundSource).toContain("'static/vendor/jquery/jquery-3.3.1.min.js'");
        expect(cssSource).toContain('body.fh-json-compact');
        expect(cssSource).toContain('min-height: 46px;');
        expect(cssSource).toContain('gap: 12px;');
        expect(cssSource).toContain('min-height: 32px;');
        expect(cssSource).toContain('width: 178px;');
        expect(cssSource).toContain('body.fh-json-compact .x-toolbar.fh-json-viewbar {\n    min-height: 38px;');
        expect(cssSource).toContain('body.fh-ui-mode-lite .fh-omni-tools');
        expect(cssSource).not.toContain('body.fh-ui-mode-lite .fh-viewbar-actions > #fhJsonExcludeSite');
        expect(cssSource).toContain('.fh-auto-mode-switch');
        expect(cssSource).toContain('.fh-json-search-box input');
        expect(cssSource).toContain('html.fh-jf .fh-viewbar-actions > .xjf-btn');
        expect(cssSource).toContain('#fhJsonExcludeSite.is-excluded');
        expect(cssSource).toContain('.t-collapse .fh-viewbar-actions > #fhJsonExcludeSite');
        expect(cssSource).toContain('.fh-viewbar-actions > .fh-collapse-icon');
        expect(cssSource).toContain('.x-toolbar.fh-json-viewbar.t-collapse .fh-viewbar-actions > .fh-collapse-icon');
        expect(cssSource).toContain('border-radius: 6px 0 0 6px;');
        expect(cssSource).toContain('border-radius: 0;');
        expect(cssSource).toContain('z-index: 2147483647;');
        expect(cssSource).toContain('pointer-events: auto;');
        expect(cssSource).toContain('body.fh-json-compact .x-toolbar.fh-json-viewbar.t-collapse');
        expect(cssSource).toContain('min-height: 30px;');
        expect(cssSource).toContain('padding: 4px 8px 4px 6px;');
        expect(cssSource).toContain('gap: 6px;');
        expect(cssSource).toContain('justify-content: center;');
        expect(cssSource).toContain('flex: 0 0 22px;');
        expect(cssSource).toContain('margin: 0 0 0 9px;');
        expect(cssSource).toContain('.fh-collapse-icon img');
        expect(cssSource).toContain('opacity: 1;');
        expect(cssSource).toContain('position: static;');
        expect(cssSource).toContain('height: 22px;');
        expect(cssSource).toContain('background: transparent;');
        expect(cssSource).toContain('box-shadow: -2px 5px 14px rgba(15, 23, 42, 0.1);');
        expect(cssSource).toContain('transform: translateX(calc(100% - 36px));');
        expect(cssSource).toContain('.x-toolbar.fh-json-viewbar.t-collapse[data-fh-json-toolbar-tucked="1"]:hover');
        expect(cssSource).toContain('.x-toolbar.fh-json-viewbar.t-collapse[data-fh-json-toolbar-tucked="1"]:focus-within');
        expect(cssSource).toContain('html.fh-jf .x-toolbar.fh-json-viewbar.t-collapse[data-fh-json-toolbar-tucked="1"]');
        expect(cssSource).toContain('html.fh-jf .x-toolbar.fh-json-viewbar.t-collapse[data-fh-json-toolbar-tucked="1"] .fh-toggle-label');
        expect(cssSource).toContain('.x-toolbar:not(.fh-json-viewbar).t-collapse .fe-feedback #toggleBtn');
        expect(cssSource).not.toMatch(/\n\.t-collapse \.fe-feedback #toggleBtn\{\s+padding-bottom: 20px;/);
        expect(cssSource).not.toContain('body.fh-json-excluded-origin');
        expect(cssSource).not.toContain('.fh-json-excluded-notice');
        expect(cssSource).toContain('#jsonSelectionMeta');
        expect(cssSource).toContain('.fh-json-search-match');
        expect(cssSource).toContain('.fh-json-search-active');
        expect(cssSource).not.toContain('.fh-json-path-pill');
        expect(cssSource).not.toContain('.fh-json-selection-meta');
        expect(cssSource).toContain('.item-line.item-line-wrap');
        expect(cssSource).toContain('.string.string-long');
        expect(cssSource).toContain('html.fh-jf .x-toolbar.fh-json-viewbar .fh-viewbar-actions > .x-other-tools');
        expect(cssSource).toContain('html.fh-jf .x-toolbar.fh-json-viewbar .fh-viewbar-actions > .x-donate-link');
        expect(cssSource).toContain('.mod-setting-panel .setting-donate-link');
        expect(cssSource).toContain('text-underline-offset: 3px;');
        expect(cssSource).toContain('html.fh-jf body.theme-dark .mod-setting-panel .setting-donate-link');
        expect(cssSource).toContain('--fh-surface: #1d2430;');
        expect(cssSource).toContain('html.fh-jf body.theme-dark .x-toolbar.fh-json-viewbar .mod-setting-panel');
        expect(cssSource).toContain('html.fh-jf body.theme-dark .mod-setting-panel label');
        expect(cssSource).toContain('html.fh-jf body.theme-dark #statusBar');
        expect(cssSource).not.toContain('#nestedEscapeParseToggle');
        expect(cssSource).not.toContain('#compactModeToggle');
        expect(backgroundSource).toContain("JSON_FORMAT_EXCLUDED_ORIGINS: ''");
        expect(backgroundSource).toContain("const rawStringOptions = ['JSON_FORMAT_EXCLUDED_ORIGINS'];");
    });

    it('popup, json, and options keep lite or omni mode preferences scoped', () => {
        const popupHtml = readSource('apps/popup/index.html');
        const popupSource = readSource('apps/popup/index.js');
        const jsonSource = readSource('apps/json-format/index.js');
        const optionsHtml = readSource('apps/options/index.html');
        const optionsSource = readSource('apps/options/index.js');

        expect(popupHtml).toContain('FeHelper 模式切换');
        expect(popupHtml).toContain("@click=\"setUiMode('lite')\"");
        expect(popupHtml).toContain("@click=\"setUiMode('omni')\"");
        expect(popupHtml).toContain("v-if=\"uiMode !== 'lite'\" class=\"fh-search\"");
        expect(popupSource).toContain("const FH_UI_MODE = 'FH_UI_MODE';");
        expect(popupSource).toContain("const FH_POPUP_UI_MODE = 'FH_POPUP_UI_MODE';");
        expect(popupSource).toContain("this.uiMode = String(meta[FH_POPUP_UI_MODE] || meta[FH_UI_MODE] || '').toLowerCase() === 'omni' ? 'omni' : 'lite';");
        expect(popupSource).toContain("[FH_POPUP_UI_MODE]: nextMode");
        expect(popupSource).toContain("key: 'lite'");
        expect(popupSource).toContain('tools: this.installedTools');
        expect(popupSource).toContain("document.documentElement.classList.toggle('fh-popup-lite-mode', isLiteMode);");
        expect(jsonSource).toContain("let JSON_FORMAT_UI_MODE = 'JSON_FORMAT_UI_MODE';");
        expect(jsonSource).toContain("chrome.storage.local.get([JSON_FORMAT_UI_MODE, FH_UI_MODE]");
        expect(jsonSource).toContain("[JSON_FORMAT_UI_MODE]: this.uiMode");
        expect(optionsHtml).toContain('FeHelper 模式');
        expect(optionsHtml).toContain("id=\"FH_UI_MODE_LITE\"");
        expect(optionsHtml).toContain("id=\"FH_UI_MODE_OMNI\"");
        expect(optionsSource).toContain("const FH_OPTIONS_UI_MODE = 'FH_OPTIONS_UI_MODE';");
        expect(optionsSource).toContain("chrome.storage.local.get([FH_OPTIONS_UI_MODE, FH_UI_MODE]");
        expect(optionsSource).toContain("[FH_OPTIONS_UI_MODE]: this.uiMode");
        expect(optionsHtml).toContain("uiMode === 'lite' ? 'fh-console-lite' : 'fh-console-omni'");
        expect(optionsHtml).toContain("{{ uiMode === 'lite' ? 'Lite 控制台' : '开发者工具控制台' }}");
        expect(optionsHtml).toContain("v-if=\"uiMode === 'omni'\"");
        expect(optionsSource).toContain("document.documentElement.classList.toggle('fh-options-lite-mode', isLiteMode);");
        expect(optionsSource).toContain("this.viewMode = 'list';");
    });

    it('Issue #603: JSONPath extraction returns copyable JSON payloads and row actions', () => {
        const html = readSource('apps/json-format/index.html');
        const source = readSource('apps/json-format/index.js');
        const css = readSource('apps/json-format/index.css');

        expect(html).toContain('复制值 JSON');
        expect(html).toContain('复制路径');
        expect(html).toContain('复制明细 JSON');
        expect(html).toContain('下载 JSON');
        expect(html).toContain('可直接使用的结果 JSON');
        expect(html).toContain('@click="copyJsonPathRowPath(result)"');
        expect(html).toContain('@click="copyJsonPathRowValue(result)"');
        expect(source).toContain('let jsonObj = parseWithBigInt(source);');
        expect(source).toContain('buildJsonPathValuePayload: function()');
        expect(source).toContain('buildJsonPathDetailsPayload: function()');
        expect(source).toContain('serializeJsonPathValue: function(value)');
        expect(source).toContain('copyJsonPathValues: function()');
        expect(source).toContain('copyJsonPathPaths: function()');
        expect(source).toContain("a.download = filename + '.json';");
        expect(source).toContain("type: 'application/json;charset=utf-8'");
        expect(source).toContain('let quotedPropMatch = indexExpr.match');
        expect(css).toContain('.jsonpath-output-panel');
        expect(css).toContain('.jsonpath-result-row');
        expect(css).toContain('.jsonpath-result-row-actions');
    });
});
